language: php

env:
  global:
    - COVERALLS=0
    - PHPCS=0

matrix:
    include:
        - php: 5.3
        - php: 5.4
          env: COVERALLS=1 PHPCS=1
        - php: 5.5
        - php: 5.6
        - php: 7
        - php: hhvm

    allow_failures:
        - php: 7
        - php: hhvm
    fast_finish: true


before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source --dev

script:
  - phunit
  - sh -c "if [ '$PHPCS' = '1' ]; then vendor/bin/phpcs -p --extensions=php --standard=PSR2 ./src ./tests ; fi"

notifications:
    on_success: never
    on_failure: always
