language: php

env:
  global:
    - COVERALLS=0
    - PHPCS=0

php:
  - 5.3
  - php: 5.4
    env: COVERALLS=1 PHPCS=1
  - 5.5
  - 5.6
  - 7
  - hhvm

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source --dev

script:
  - phunit
  - sh -c "if [ '$PHPCS' = '1' ]; then vendor/bin/phpcs -p --extensions=php --standard=PSR2 ./src ./tests ; fi"

matrix:
  allow_failures:
    - php: 7
    - php: hhvm
  fast_finish: true

notifications:
    on_success: never
    on_failure: always
